// Generated by CoffeeScript 1.10.0
(function() {
  var expect, path, tester;

  path = require('path');

  expect = require('chai').expect;

  tester = require('gitbook-tester');

  describe('SVG Inline Gitbook plugin', function() {
    return it('should load and generate basic content', function(done) {
      this.timeout(5000);
      return tester.builder().withLocalPlugin(path.join(__dirname, '..')).withContent('Hello World!').create().then(function(result) {
        var e, error;
        try {
          expect(result[0].content).to.equal('<p>Hello World!</p>');
          return done();
        } catch (error) {
          e = error;
          return done(e);
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=feature.js.map
