// Generated by CoffeeScript 1.10.0
(function() {
  var expect, path, tester;

  path = require('path');

  expect = require('chai').expect;

  tester = require('gitbook-tester');

  describe('The module should load ', function() {
    return describe('as a nodejs module', function() {
      var plugin;
      plugin = require('..');
      it('should load', function() {
        return expect(plugin).to.exist;
      });
      return it('and should have basic gitbook plugin declarations', function() {
        expect(plugin.website).to.exist;
        expect(plugin.blocks).to.exist;
        expect(plugin.filters).to.exist;
        return expect(plugin.hooks).to.exist;
      });
    });
  });

}).call(this);

//# sourceMappingURL=module.js.map
