// Generated by CoffeeScript 1.10.0
(function() {
  var chai, expect, path, tester;

  path = require('path');

  chai = require('chai');

  expect = chai.expect;

  tester = require('gitbook-tester');

  describe('SVG Inline Gitbook plugin', function() {
    return it('should execute without hanging (wait, what?)', function(done) {
      this.timeout(10000);
      return tester.builder().withLocalPlugin(path.join(__dirname, '..')).withContent('Hello World!').create().then(function(result) {
        var e, error;
        try {
          expect(result[0].content).to.equal('<p>Hello World!</p>');
          return done();
        } catch (error) {
          e = error;
          return done(e);
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=tester.js.map
